name = "NeuroPlanner"
uuid = "628e68bf-2596-4972-a53b-69fd3c43dbca"
authors = ["Tomas Pevny"]
version = "0.1.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
Mill = "1d0525e4-8992-11e8-313c-e310e1f6ddea"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicPlanners = "b6fe5377-9711-4fad-95b0-be4eed71ecbb"

[compat]
Flux = "0.13"
Mill = "2.8.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
