name = "NeuroPlanner"
uuid = "628e68bf-2596-4972-a53b-69fd3c43dbca"
authors = ["Tomas Pevny"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HierarchicalUtils = "f9ccea15-0695-44b9-8113-df7c26ae4fa9"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Mill = "1d0525e4-8992-11e8-313c-e310e1f6ddea"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticBitSets = "72d6c30d-a10b-4e7e-bc09-3079d9530bdf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicPlanners = "b6fe5377-9711-4fad-95b0-be4eed71ecbb"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"

[compat]
Accessors = "0.1.32"
ChainRulesCore = "1.15, 1.16"
Flux = "0.13, 0.14"
MLUtils = "0.4"
Mill = "2.10"
PDDL = "0.2"
Statistics = "1"
SymbolicPlanners = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
