[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
NeuroPlanner = "628e68bf-2596-4972-a53b-69fd3c43dbca"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlanningDomains = "34fa33c8-33e3-4e77-bac8-de592315aba2"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicPlanners = "b6fe5377-9711-4fad-95b0-be4eed71ecbb"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
