[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AllocArrays = "5c00bae2-1499-4716-9206-27f63fd08a44"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
LIBLINEAR = "2d691ee1-e668-5016-a719-b2531b85e0f5"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
Mill = "1d0525e4-8992-11e8-313c-e310e1f6ddea"
NeuroPlanner = "628e68bf-2596-4972-a53b-69fd3c43dbca"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlanningDomains = "34fa33c8-33e3-4e77-bac8-de592315aba2"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProfileCanvas = "efd6af41-a80b-495e-886c-e51b0c7d77a3"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
SymbolicPlanners = "b6fe5377-9711-4fad-95b0-be4eed71ecbb"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
