[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
Mill = "1d0525e4-8992-11e8-313c-e310e1f6ddea"
NeuroPlanner = "628e68bf-2596-4972-a53b-69fd3c43dbca"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlanningDomains = "34fa33c8-33e3-4e77-bac8-de592315aba2"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProfileSVG = "132c30aa-f267-4189-9183-c8a63c7e05e6"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicPlanners = "b6fe5377-9711-4fad-95b0-be4eed71ecbb"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
