[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
Mill = "1d0525e4-8992-11e8-313c-e310e1f6ddea"
NeuroPlanner = "628e68bf-2596-4972-a53b-69fd3c43dbca"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlanningDomains = "34fa33c8-33e3-4e77-bac8-de592315aba2"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicPlanners = "b6fe5377-9711-4fad-95b0-be4eed71ecbb"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
Yota = "cd998857-8626-517d-b929-70ad188a48f0"
